feat(core): added show and hide delay to tooltip and hint directives
TinkoffCreditSystems/taiga-ui pull request #205
Opened 2021-02-03 20:46 UTC by fynnfeldpausch

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [x] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

Closes #202 

## What is the new behavior?

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

## Other information

2021-02-25 12:45 UTC, MarsiBarsi approved these changes

2021-02-25 12:49 UTC, waterplea requested changes
Sorry for the delay, please take a look at the comment and we're good to merge.

2021-02-25 12:49 UTC, waterplea commented on projects/core/components/tooltip/tooltip.component.ts
> +    showDelay = 0;
This should have default values, 500 and 200

2021-05-03 18:34 UTC, KarimovDev commented
Hi, @fynnfeldpausch! 
Do you need some help here? I can push the PR includes this feature and fixes above

2021-05-04 08:50 UTC, waterplea commented
> Hi, @fynnfeldpausch!
> Do you need some help here? I can push the PR includes this feature and fixes above

As far as I know @fynnfeldpausch got pulled to another project, unrelated to Taiga UI so he paused all his contributions. Feel free to pick it up, @KarimovDev if that issue is relevant to you.

2021-05-12 15:05 UTC, closed without merging