Table first draft
TinkoffCreditSystems/taiga-ui pull request #223
Opened 2021-02-10 17:23 UTC by waterplea

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [ ] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

Closes #

## What is the new behavior?

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [ ] No

## Other information

2021-02-12 20:47 UTC, waterplea reviewed
Needs work

2021-02-12 20:47 UTC, waterplea commented on projects/addon-table/components/resizable-column/resizable-column.style.less
> +    z-index: 5;
Rework this according to the new design

2021-02-12 20:47 UTC, waterplea commented on projects/addon-table/components/reorder/reorder.component.ts
> +    items: readonly T[] = [];
Need to add a way to show the template and example of usage with table

2021-02-12 20:47 UTC, waterplea commented on projects/addon-table/components/table/head.directive.ts
> +    ): _ctx is TuiContextWithImplicit<T[K]> {
Wrong context type, review the whole directive and its usage

2021-02-12 20:47 UTC, waterplea commented on projects/addon-table/components/table/table.providers.ts
> +        useValue: TuiAppearance.Table,
Redesigning this appearance is a breaking change

2021-02-12 20:47 UTC, waterplea commented on projects/addon-table/components/table/table.style.less
> +    position: sticky;
Need to make sticky optional

2021-02-12 20:47 UTC, waterplea commented on projects/addon-table/components/table/table.style.less
> +    &:after {
New design has this shadow removed

2021-02-12 20:47 UTC, waterplea commented on projects/addon-table/components/table/table.template.html
> +<ng-container *tuiLet="entries$ | async as entries">
This is unnecessary for the header, can be moved to tbody

2021-02-12 20:47 UTC, waterplea commented on projects/addon-table/components/table/table.template.html
> +    <tr *ngFor="let row of sorted" class="row">
Need to add tbody and ability to use multiple tbodies with labels and expand/collapse, but need final design first

2021-02-12 20:47 UTC, waterplea commented on projects/addon-table/components/table/thead.directive.ts
> +    @HostBinding('$.class._stuck')
Need to go over the whole library and update such bindings. See underline component.

2021-02-12 20:47 UTC, waterplea commented on projects/cdk/package.json
> +        "@tinkoff/ng-event-plugins": "2.1.0",
Bump all versions to 2.1.1

2021-02-12 20:47 UTC, waterplea commented on projects/core/components/primitive-textfield/primitive-textfield.style.less
> +    height: 0;
Make sure this doesn't break anything

2021-02-12 20:47 UTC, waterplea commented on projects/core/components/primitive-textfield/primitive-textfield.template.html
> +            <span aria-hidden="true" class="value">{{value}}</span>
Is aria-hidden necessary for visibility hidden?

2021-02-12 20:47 UTC, waterplea commented on projects/core/directives/textfield-controller/textfield-controller.provider.ts
> +    const change$ = merge(...controllers.map(({change$}) => change$ || NEVER)).pipe(
See again if this could be properly typed

2021-02-12 20:47 UTC, waterplea commented on projects/core/styles/theme/wrapper/table.less
> -        border-width: 1px;
Breaking changes here

2021-02-12 20:47 UTC, waterplea commented on projects/demo/src/modules/tables/table/examples/2/index.less
> +    order: -1;
Think about this again

2021-02-12 20:47 UTC, waterplea commented on projects/demo/src/modules/tables/table/examples/import/import-module.txt
> +import {TuiActionModule} from '@taiga-ui/kit';
This is wrong

2021-02-12 20:47 UTC, waterplea commented on projects/demo/src/modules/tables/table/examples/2/index.html
> +    <div class="loh"></div>
No loh please

2021-02-12 20:47 UTC, waterplea commented on projects/addon-table/components/table/table.style.less
> +    .createStackingContext();
Need a way to customize borders and hover effects

2021-02-12 20:47 UTC, waterplea commented on projects/demo/src/modules/tables/table/table.template.html
> +        <p>Interactive table main component.</p>
Need better documentation

2021-02-12 20:47 UTC, waterplea commented on projects/kit/components/input-number/input-number.template.html
> +    tuiTextfieldInputMode="decimal"
This doesn't work, @MarsiBarsi

2021-02-15 09:26 UTC, MarsiBarsi requested changes

2021-02-15 09:26 UTC, MarsiBarsi commented on projects/addon-table/components/table/table.template.html
> +                    <td class="cell" [class.cell_number]="isNumber(row[key])">
thank about row span and col span

2021-02-15 09:26 UTC, MarsiBarsi commented on projects/demo/src/modules/app/pages.ts
> +                keywords: 'таблица, data, cell',
tr, th, td, row, col, grid

2021-02-15 09:26 UTC, MarsiBarsi commented on projects/demo/src/modules/tables/table/examples/1/index.ts
> +    ];
as const?

2021-02-15 09:26 UTC, MarsiBarsi commented on projects/demo/src/modules/tables/table/examples/1/index.ts
> +    ];
or let's make an interface because we want to spread best practices in our samples

2021-02-15 09:26 UTC, MarsiBarsi commented on projects/demo/src/modules/tables/table/examples/import/insert-template.txt
> +<tui-action [icon]="icon" (click)="onClick()">
this is also wrong

2021-02-15 09:26 UTC, MarsiBarsi commented on projects/kit/components/input-number/input-number.template.html
> +    tuiTextfieldInputMode="decimal"
What a pity!

2021-02-20 08:20 UTC, MarsiBarsi commented
if I change value of this input and press Tab to go to the next cell, it triggers a recalculation of Total and rerendering a table and table loses focus
![image](https://user-images.githubusercontent.com/10106368/108589013-50d99b80-736d-11eb-9b93-c24bde6bb4a5.png)

2021-02-20 08:21 UTC, MarsiBarsi commented
> if I change value of this input and press Tab to go to the next cell, it triggers a recalculation of Total and rerendering a table and table loses focus
> ![image](https://user-images.githubusercontent.com/10106368/108589013-50d99b80-736d-11eb-9b93-c24bde6bb4a5.png)

Moreover, it loses focus pressing Tab after any editing

2021-02-24 11:57 UTC, MarsiBarsi commented on projects/addon-table/components/table/tbody/tbody.template.html
> +<ng-container *ngIf="open">
maybe `&& row` and no Elvis

2021-02-24 11:57 UTC, MarsiBarsi commented on projects/addon-table/components/table/td/td.style.less
> +    @supports (-moz-appearance: none) {
check if it still needed

2021-02-24 11:57 UTC, MarsiBarsi commented on projects/core/components/dialog/dialog.providers.ts
> +        : NEVER;
close$

2021-02-24 11:57 UTC, MarsiBarsi commented on projects/core/components/wrapper/wrapper.module.ts
> +    schemas: [NO_ERRORS_SCHEMA],
delete

2021-02-24 11:57 UTC, MarsiBarsi commented on projects/demo/src/modules/tables/table/examples/2/index.html
> +            <td *tuiCell="''" tuiTd>
add "actions" or smth

2021-02-24 11:57 UTC, MarsiBarsi commented on projects/demo/src/modules/tables/table/examples/3/index.html
> +                    <th *ngIf="value < 1000" class="second" tuiTd>
<= maybe

2021-02-24 14:04 UTC, MarsiBarsi approved these changes
wow!

2021-02-25 10:11 UTC, merged