feat(core): `NightThemeService` add new service
TinkoffCreditSystems/taiga-ui pull request #226
Opened 2021-02-15 16:23 UTC by waterplea

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [ ] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

Closes #

## What is the new behavior?

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [ ] No

## Other information

2021-02-15 16:23 UTC, waterplea commented
Tests are coming

2021-02-15 17:37 UTC, MarsiBarsi requested changes
please add it into index.ts

2021-02-15 17:38 UTC, MarsiBarsi commented
add maybe some tests :))

2021-03-29 17:00 UTC, MarsiBarsi approved these changes

2021-03-29 17:00 UTC, merged