fix(all): added link to source code and fixed routing
TinkoffCreditSystems/taiga-ui pull request #273
Opened 2021-03-09 14:38 UTC by nikitadubinsk

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [x] Bugfix
-   [ ] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

Closes #

## What is the new behavior?

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

## Other information

2021-03-10 04:45 UTC, Mistydjones007 approved these changes

2021-03-10 08:10 UTC, MarsiBarsi commented on projects/demo/src/modules/app/app.providers.ts
> +            if (context.package) {
обязательно почитай про практику `early return`, она очень сильно помогает сделать код более читабельным

в целом по тому, как писать понятный код, могу посоветовать "Чистый код" Роберта Мартина

2021-03-10 09:16 UTC, nikitadubinsk commented on projects/demo/src/modules/app/app.providers.ts
> +        useValue: (context: any) => {
да, как-то забыл о типе, уже исправил

2021-03-10 09:17 UTC, nikitadubinsk commented on projects/demo/src/modules/app/app.providers.ts
> +            if (context.package) {
исправил, надеюсь правильно

2021-03-11 05:17 UTC, MarsiBarsi requested changes

2021-03-11 05:17 UTC, MarsiBarsi commented on projects/demo/src/modules/app/app.providers.ts
> +            return `https://github.com/TinkoffCreditSystems/taiga-ui/tree/main/projects/${context.path}`;
смотри еще какой момент — 'https://github.com/TinkoffCreditSystems/taiga-ui/tree/main/projects' повторяется дважды. Если нам понадобится однажды заменить ссылку, то в лучшем случае придется заменять два раза, а в худшем — во втором забудем 

давай вынесем в константу локальную над условием и будем переиспользовать в обоих return

2021-03-11 05:17 UTC, MarsiBarsi commented on projects/demo/src/modules/app/app.providers.ts
> +                ).replace(/[A-Z]/g, (m: any) => '-' + m.toLowerCase())}`;
тут точно не any :)

должно быть можно вовсе вот так написать `m => '-' + m.toLowerCase()` (без скобок с типом -> тип подхватится атвоматически)

2021-03-11 09:42 UTC, MarsiBarsi approved these changes

2021-03-15 06:17 UTC, MarsiBarsi approved these changes

2021-03-15 06:17 UTC, MarsiBarsi commented on projects/demo/src/modules/components/error/error.template.html
> +<tui-doc-page header="Error" package="CORE" type="components" type="components">
дважды, но я с веб интерфейса пофишу

2021-03-15 06:17 UTC, merged