fix(kit): fix fixed scrolling with arrows in input-tag
TinkoffCreditSystems/taiga-ui pull request #334
Opened 2021-04-07 12:40 UTC by nikitadubinsk

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [ ] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

Closes #

## What is the new behavior?

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [ ] No

## Other information

2021-04-12 09:17 UTC, waterplea commented on projects/kit/components/input-tag/input-tag.component.ts
> +                tag.nativeElement.parentElement?.parentElement?.parentElement;
Так не надо делать никогда ) Придумай как лучше получить референс

2021-04-12 09:17 UTC, waterplea commented on projects/kit/components/input-tag/input-tag.component.ts
> +            tag.nativeElement.focus({preventScroll: true});
На всякий случай лучше оставь утилитный метод setNativeFocused. Ну и preventScroll тут роли не играет, убирай

2021-04-12 09:17 UTC, waterplea commented on projects/kit/components/input-tag/input-tag.component.ts
> +                parentTag?.scrollBy(-tag.nativeElement.clientWidth, 0);
У scrollBy поддержка вроде приемлимая, но не слишком хорошая:
https://caniuse.com/?search=scrollBy
Если бы это был грейсфул дерадейшн оставили бы, но тут бахнет undefined is not a function. Либо добавь проверку, либо перепиши на `scrollLeft = `

2021-04-12 09:17 UTC, waterplea commented on projects/kit/components/input-tag/input-tag.component.ts
> +            const parentTag =
Почти одинаковый код. В функцию бы его как-то общую загнать

2021-04-26 13:40 UTC, waterplea requested changes

2021-04-26 13:40 UTC, waterplea commented on projects/kit/components/input-tag/input-tag.template.html
> +                    #scrollBar
Не нужно

2021-04-26 13:40 UTC, waterplea commented on projects/kit/components/input-tag/input-tag.component.ts
> +    @ViewChild('scrollBar', {read: ElementRef})
Можно TuiScrollbarComponent написать

2021-04-26 13:40 UTC, waterplea commented on projects/kit/components/input-tag/input-tag.component.ts
> +        if (tag && this.scrollBar) {
Давай обратное условие с ранним выходом.

2021-04-26 13:40 UTC, waterplea commented on projects/kit/components/input-tag/input-tag.component.ts
> +            if (
Эта чёрная арифметика в обе стороны работает? )

2021-04-26 14:18 UTC, nikitadubinsk commented on projects/kit/components/input-tag/input-tag.component.ts
> +            if (
По крайней мере все мои тесты давали положительный результат

2021-04-27 14:49 UTC, waterplea requested changes
Коммент + закинь, пожалуйста, приватный метод пониже к остальным приватным. И давай в этом же PR`е добавь providedIn: 'root' на скролл сервис, чтоб не разводить ПРы на совсем мелочь.

2021-04-27 14:49 UTC, waterplea commented on projects/kit/components/input-tag/input-tag.component.ts
> +        } else {
else не нужен. Суть раннего выхода, как раз, в том, чтобы не смещать вправо основной ход выполнения.

2021-04-27 14:49 UTC, waterplea commented on projects/kit/components/input-tag/input-tag.component.ts
> +        if (!(tag && this.scrollBar)) {
Давай лучше без группировки, легче читать, когда меньше скобок - обычно так пишем.

2021-04-28 07:47 UTC, waterplea approved these changes

2021-04-28 08:13 UTC, merged