feat(core): tooltip show hide delay
TinkoffCreditSystems/taiga-ui pull request #379
Opened 2021-05-07 21:43 UTC by KarimovDev

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [x] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

Closes #202 

## What is the new behavior?

Copy of #205 with implementation of review notes

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

2021-05-11 14:35 UTC, waterplea requested changes
Small comments. @MarsiBarsi please take a look at this PR as well. Do you think hint controller has to be involved as well?

2021-05-12 11:42 UTC, KarimovDev commented on projects/core/directives/pointer-hint/pointer-hint.directive.ts
> +                    return of(visible).pipe(
Done

2021-05-12 11:42 UTC, KarimovDev commented on projects/demo/src/modules/components/tooltip/tooltip.component.ts
> +    showDelay = 0;
You are right, I've fixed it

2021-05-12 11:44 UTC, KarimovDev commented
> Small comments. @MarsiBarsi please take a look at this PR as well. Do you think hint controller has to be involved as well?

I think It has sense. I've added delay settings to hint controller

2021-05-12 12:00 UTC, MarsiBarsi commented
Hey @KarimovDev thanks for your PR and mentioning me. I'll take a look today

2021-05-12 12:27 UTC, MarsiBarsi approved these changes

2021-05-12 15:06 UTC, waterplea approved these changes

2021-05-12 17:21 UTC, merged