Implement new breadcrumbs wrapper
TinkoffCreditSystems/taiga-ui pull request #412
Opened 2021-05-18 12:16 UTC by vakhramoff

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [x] Tests for the changes have been added (for bug fixes / features)
-   [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [x] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

Closes #388

## What is the new behavior?

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

## Other information

2021-05-18 15:18 UTC, waterplea requested changes
Мелкие комментарии

2021-05-18 15:18 UTC, waterplea commented on projects/kit/components/breadcrumbs/breadcrumb.directive.ts
> +    constructor(@Inject(TemplateRef) readonly template: TemplateRef<{}>) {}
Это не нужно

2021-05-18 15:18 UTC, waterplea commented on projects/kit/components/breadcrumbs/breadcrumbs-wrapper.component.ts
> +    readonly items: QueryList<TemplateRef<TuiLinkComponent>> = EMPTY_QUERY;
Контекст `{}`, не компонент, ты ведь без контекста создаёшь :)

2021-05-18 15:18 UTC, waterplea commented on projects/kit/components/breadcrumbs/breadcrumbs-wrapper.component.ts
> +    @HostBinding('attr.data-tui-host-size')
Давай просто data-size, раньше длинно писали, потом решили - нафига? )

2021-05-18 15:18 UTC, waterplea commented on projects/kit/components/breadcrumbs/breadcrumbs-wrapper.component.ts
> +        this.change$.next();
Давай пустой метод сделаем, оно тут ни к чему

2021-05-18 15:18 UTC, waterplea commented on projects/kit/components/breadcrumbs/breadcrumbs-wrapper.component.ts
> +    readonly change$: Subject<void> = new Subject<void>();
Тип в таком случае явно выводится, можно не писать. Да и ниже тоже можно не писать, так как приходит из implements TuiModeDirective

2021-05-18 15:18 UTC, waterplea commented on projects/kit/components/breadcrumbs/breadcrumbs-wrapper.style.less
> +    &[data-tui-host-size='m'] {
Можно сэкономить чуть-чуть букв и дефолтный размер m вынести просто в :host

2021-05-18 15:18 UTC, waterplea commented on projects/kit/components/breadcrumbs/breadcrumbs-wrapper.style.less
> +// specificity is the reason of this selector
Этот блок можно убрать

2021-05-18 15:18 UTC, waterplea commented on projects/kit/components/breadcrumbs/breadcrumbs-wrapper.template.html
> +    <ng-container [ngTemplateOutlet]="item"></ng-container>
Давай через *, привычнее видеть на контейнере *, на шаблоне - [].

2021-05-18 17:44 UTC, vakhramoff commented on projects/kit/components/breadcrumbs/breadcrumbs-wrapper.component.ts
> +    readonly change$: Subject<void> = new Subject<void>();
Без него ругается)

2021-05-18 18:33 UTC, vakhramoff commented
Почему-то локально тесты падают, а тут всё ок о_О

2021-05-19 07:53 UTC, waterplea commented on projects/demo/src/modules/components/badged-content/examples/2/index.ts
> +    styleUrls: ['./index.style.less'],
Why the rename? :)

2021-05-19 07:54 UTC, waterplea commented on projects/demo/src/modules/components/breadcrumbs/examples/1/index.html
> +            [routerLinkActiveOptions]="item.routerLinkActiveOptions || {exact: false}"
Давай уберём ||. А то у тебя пересоздаваться объект будет на каждый цикл проверки изменений

2021-05-19 07:55 UTC, waterplea commented on projects/demo/src/modules/components/badged-content/badged-content.component.ts
> +        LESS: example2Less,
А это вообще всё к чему? )

2021-05-19 07:56 UTC, waterplea commented on projects/demo/src/modules/components/breadcrumbs/examples/1/index.style.less
> +        color: var(--tui-text-03);
А что, без этого разве цвет другой? Я бы забил вообще на pointer-events: none. Ангуляр и так не перезагрузит тот же роут по клику.

2021-05-19 07:57 UTC, waterplea commented on projects/demo/src/modules/components/breadcrumbs/examples/1/index.ts
>              routerLinkActiveOptions: {exact: true},
Мне кажется этот options роли не играет в данной ситуации. Давай уберём? Заодно и не понадобится тот || в шаблоне

2021-05-19 07:57 UTC, waterplea commented on projects/kit/components/breadcrumbs/breadcrumb.directive.ts
> +    constructor() {}
Не нужен )

2021-05-19 07:59 UTC, waterplea commented on projects/kit/components/breadcrumbs/breadcrumbs-wrapper.style.less
> +        font: var(--tui-font-text-s);
Забыл  перенести в :host дефолтное значение

2021-05-19 09:12 UTC, merged