chore(demo): add sanitizer info to icons page
TinkoffCreditSystems/taiga-ui pull request #494
Opened 2021-06-18 13:12 UTC by vladimirpotekhin

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [ ] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

Closes #454 

## What is the new behavior?

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

## Other information

2021-06-22 14:53 UTC, MarsiBarsi requested changes

2021-06-22 14:53 UTC, MarsiBarsi commented on projects/demo/src/modules/components/editor/editor.template.html
> +            use a <a tuiLink href="/icon-set#sanitizer">sanitizer</a> with this
routerLink

2021-06-22 14:53 UTC, MarsiBarsi commented on projects/demo/src/modules/customization/icon-set/icon-set.template.html
> +            as sanitizer. This library implements DOMPurify as Angular Sanitizer
nit: as a sanitizer

2021-06-22 14:53 UTC, MarsiBarsi commented on projects/demo/src/modules/customization/icon-set/icon-set.template.html
> +            you need to provide TUI_SANITIZER token, which is responsible for
<code>TUI_SANITIZER</code>

2021-06-22 14:53 UTC, MarsiBarsi commented on projects/demo/src/modules/customization/icon-set/icon-set.template.html
> +            as sanitizer. This library implements DOMPurify as Angular Sanitizer
let's make DOMPurify a link to the project

2021-06-23 17:35 UTC, waterplea approved these changes
Small comment, other than that LGTM

2021-06-23 17:35 UTC, waterplea commented on projects/demo/src/modules/customization/icon-set/icon-set.template.html
> +            If you use unsafe icons or have kind of WYSISYG editor in your app
> or Editor component (with a link to it)

2021-06-24 13:38 UTC, MarsiBarsi approved these changes

2021-06-24 14:53 UTC, merged