fix(kit): fix Firefox issue with input right padding for case when icon or cleaner on the right
TinkoffCreditSystems/taiga-ui pull request #612
Opened 2021-08-09 10:29 UTC by k-tar

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ x] Bugfix
-   [ ] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

In Firefox, padding for input is being ignored until text's width less than input's width. Some text become unable to see under the cleaner/icons.
![screenshot](https://user-images.githubusercontent.com/6583155/128692804-1a526785-294c-4a65-a0f1-9d7423b7fa46.png)

## What is the new behavior?

Replaced paddings with invisible borders. 

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [x ] No

## Other information

Checked that fix works and does not break anything:
- Chrome, Firefox, Safari – on MacOS;
- Chrome – on Android;
- Safari – on iOS.

2021-09-03 08:48 UTC, waterplea requested changes
Thank you for this PR! Please take a look at my comments

2021-09-03 08:48 UTC, waterplea commented on projects/core/styles/mixins/textfield.less
> +        border-width: 0 16px;
Let's keep rems here and instead change the function to rem itself

2021-09-03 08:48 UTC, waterplea commented on projects/core/components/primitive-textfield/primitive-textfield.template.html
> +        [style.borderLeftWidth.px]="borderLeft"
Please change all `.px` to `.rem`

2021-09-03 08:48 UTC, waterplea commented on projects/core/utils/miscellaneous/get-border.ts
> +const BORDER_SMALL = 12;
Let's change all these to REMs:
```js
const BORDER_SMALL = 0.75;
const BORDER_LARGE = 1;
const ITEM_SIZE = 1.5;
const CONTENT_SIZE = 2.5;
```

2021-09-03 08:48 UTC, waterplea commented on projects/core/components/primitive-textfield/primitive-textfield.style.less
> +    border-style: solid;
Can we maybe change this to a shorthand `border: 0 solid transparent;`?

2021-09-10 08:39 UTC, waterplea commented
@k-tar we plan to start regular releases on Mondays, if you fix comments today we can get this into next release ;)

2021-09-10 09:51 UTC, k-tar commented
@waterplea Everything resolved

2021-09-10 12:42 UTC, waterplea requested changes
A few little comments + tests need to be updated to use REMs. Please check the final result on Safari and iOS, I don't have those near me these days and they tend to break things :)

2021-09-10 12:42 UTC, waterplea commented on projects/core/components/primitive-textfield/primitive-textfield.template.html
> +        [style.borderLeftWidth.px]="borderLeft"
These two still have `px`

2021-09-10 12:42 UTC, waterplea commented on projects/core/styles/mixins/textfield.less
> +    border-left-width: 0.75rem;
Can it be `border-width: 0 0.75rem`?

2021-09-10 23:44 UTC, k-tar commented
@waterplea 

Fixed everything and found one more required change for icon paddings (in primitive-textfield.component.ts).

Safari and iOS was checked (iOS only in Xcode Simulator, I haven't a real device, but Simulator was correct all time I use it for CSS checks), works fine and everything as before, except behaviour related to the issue.

2021-09-11 07:53 UTC, waterplea approved these changes

2021-09-13 07:53 UTC, merged