feat(demo): add SSR support
TinkoffCreditSystems/taiga-ui pull request #64
Opened 2020-12-21 17:40 UTC by waterplea

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [ ] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [ ] No

## Other information

2020-12-21 19:48 UTC, MarsiBarsi requested changes

2020-12-21 19:48 UTC, MarsiBarsi commented on angular.json
> +                        "outputPath": "dist/demo/browser",
это сломает публикацию на pages
тогда тебе в deploy.yml над на dist/demo/browser тоже менять

2020-12-21 19:48 UTC, MarsiBarsi commented on angular.json
> +                        "production": {}
а зачем она, если ничего не делает?

2020-12-21 20:16 UTC, waterplea commented on angular.json
> +                        "production": {}
Хз, так ангуляр нагенерил. Даже в жамиге у нас оно так же. Оставлю на всякий случай, всё равно это пререндер, который мы не трогаем.

2020-12-21 20:16 UTC, waterplea commented on angular.json
> +                        "outputPath": "dist/demo/browser",
Поправил yml

2020-12-22 12:34 UTC, MarsiBarsi approved these changes

2020-12-22 12:35 UTC, merged

2025-04-18 08:16 UTC, waterplea commented
WTF, @nx-cloud?