feat(core): `Dialog` add directive for declarative dialogs
TinkoffCreditSystems/taiga-ui pull request #745
Opened 2021-09-22 11:38 UTC by waterplea

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [ ] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

Closes #

## What is the new behavior?

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [ ] No

## Other information

2021-09-23 06:57 UTC, nsbarsukov requested changes

2021-09-23 06:57 UTC, nsbarsukov commented on projects/demo/src/modules/services/dialogs/dialogs.template.html
> +            <tui-dialog-example-6></tui-dialog-example-6>
Let's add here
https://github.com/TinkoffCreditSystems/taiga-ui/blob/main/projects/demo-integrations/cypress/tests/core/dialogs/dialogs.spec.ts

```js
it('Dialog with directive works', () => {
    cy.goToDemoPage(DIALOG_PAGE_URL);

    cy.get(`tui-dialog-example-6 button`).first().click();
    waitKitDialog();
    cy.get('tui-dialog').matchImageSnapshot('dialog-directive');
});
```

2021-09-23 08:49 UTC, waterplea commented on projects/demo/src/modules/services/dialogs/dialogs.template.html
> +            <tui-dialog-example-6></tui-dialog-example-6>
Done

2021-09-23 13:18 UTC, vladimirpotekhin approved these changes

2021-09-24 09:17 UTC, nsbarsukov approved these changes

2021-09-24 12:41 UTC, merged